### ISSUE TITLE
Fsync interface has changed

### ISSUE THREAD

**Issue by wereii** [weirddan455/futex-test#1]
Fsync interface has changed in latest patches. Also these patches were merged upstream in kernel `5.16`.
Currently it seems that even older (GE's) Proton versions can't detect this new fsync properly.

https://github.com/ValveSoftware/wine/commit/120c1d7a3553bd101d67a02f1aad6514fa118b84#diff-5e5c817e009fbb854f97c5164ec0d248d77659f32d357a8e9d548afd13e9028eR63

https://github.com/ValveSoftware/wine/blob/120c1d7a3553bd101d67a02f1aad6514fa118b84/server/fsync.c#L63

**Comment by weirddan455** [comment]
Yea, I can take a look at that once I get a 5.16 kernel.  5.16 is in rc-7 right now.  I generally don't run RC kernels but I suspect it'll be released soon.

**Comment by weirddan455** [comment]
5.16 is now out and I've added a test for the mainline futex2 in commit: https://github.com/weirddan455/futex-test/commit/9ea9936389d14854bd9241f56293d55966cb1b9e

Note that there's probably a better test for this in the Linux kernel sources in tools/testing/selftests/futex/functional/futex_waitv.c (does require downloading the entire kernel source as it depends on some header files in there.)

For my test, I just hardcoded in the constants and struct definitions so it will compile with older headers.  Probably only works on x86_64 as syscall numbers will be different on other platforms.
