### ISSUE TITLE
kernel 5.16.2-200.fc35.x86_64

### ISSUE THREAD

**Issue by didierga** [weirddan455/futex-test#2]
Hi,

I tried to run futex-test on kernel 5.16.2-200.fc35.x86_64 and I get this result:

```
$ ./futex-test
Kernel name: Linux
Kernel version 5.16.2-200.fc35.x86_64
Linux kernel detected
futex-FUTEX_WAIT_MULTIPLE: Function not implemented
futex-FUTEX_WAIT_MULTIPLE: Function not implemented
FUTEX_WAIT_MULTIPLE test failed
access /sys/kernel/futex2: No such file or directory
futex2 test failed
Mainline (kernel 5.16+) futex2 test successful
$
```

What is wrong ?

**Comment by weirddan455** [comment]
Nothing's wrong.  I get the same results on my stock 5.16 kernel.  The failed tests are for the older implementations.  They were kernel patches that never got merged into the mainline kernel but were widely used in custom kernels.

You will need to check that your wine/proton version supports the new 5.16 implementation if you want to take advantage of this but I'm not sure what the status of that is.
