### ISSUE TITLE
Information: Arch Linux package in the AUR.

### ISSUE THREAD

**Issue by dreirund** [weirddan455/futex-test#4]
Note: There is now an Arch Linux package of this in the [AUR](https://wiki.archlinux.org/title/Arch_User_Repository): [`futex-test-git`](https://aur.archlinux.org/pkgbase/futex-test-git).

If you want, you can link to it in your [`README.md`](https://github.com/weirddan455/futex-test/blob/main/README.md).

Regards!

**Comment by weirddan455** [comment]
Added link to AUR
