### ISSUE TITLE
[Feature request] Add `-h`|`--help` option.

### ISSUE THREAD

**Issue by dreirund** [weirddan455/futex-test#5]
In the [`README.md`](https://github.com/weirddan455/futex-test/blob/main/README.md) it is documented that the programme accepts a `--verbose` option.

To easy finding out about possible options, this is a feature request to add options `-h` and `--help` that print out a help text about usage/ accepted options.

*(And optionally, to add that the software exits with error and error message if an unsupported option is provided.)*

Regards!

**Comment by weirddan455** [comment]
Added help message

**Comment by dreirund** [comment]
> Added help message

GReat!
